Exception handling and recoding some functions

diff --git a/MyScript b/MyScript
--- a/MyScript
+++ b/MyScript
@@ -1,6 +1,7 @@
-#!
+#!/bin/bash
 #PROGRAMM FILE: MyScript
 #PROGRAMMER: Abbasguliev Rolan
+
 param1=$1
 param2=$2
 param3=$3
@@ -14,40 +15,62 @@ YELLOW='\033[1;33m'
 ORANGE='\033[0;33m'
 NC='\033[0m'
 
+isnum()
+{
+  #re='^[0-9]+$'
+  if [ -n "$1" ] && [ "$1" -eq "$1" ] 2>/dev/null; then 
+    return 0
+  else
+    return 1
+  fi
+}
 
 calc()
-{
-  case $param2 in 
-    sum)
-         echo "RESULT: $(( param3 + param4 ))"
-         ;;
-    sub)
-         echo "RESULT: $(( param3 - param4 ))"
-         ;;
-    mul) 
-         echo "RESULT: $(( param3 * param4 ))"
-         ;;
-    div)			 	
-         echo "RESULT: $(( param3 / param4 ))"
-         ;;
-      *)
-         echo -e "${RED}CALC FUNCTION ERROR${NC}" 
-         exit 1
-         ;; 
-    esac	
+{  
+  call_math=$1
+  arg1=$2
+  arg2=$3 
+  if ! $(isnum $arg1); then 
+    echo -e "${RED}First argument is not number ${NC}"
+    return 1
+  fi
+  if ! $(isnum $arg2); then
+    echo -e "${RED}Second argument is not number${NC}"
+    return 1
+  fi
+ 
+       
+case $call_math in 
+   sum)
+     echo "RESULT: $(( arg1 + arg2 ))"
+     ;;
+   sub)
+     echo "RESULT: $(( arg1 - arg2 ))"
+     ;;
+   mul) 
+     echo "RESULT: $(( arg1 * arg2 ))"
+     ;;
+   div)			 	
+     echo "RESULT: $(( arg1 / arg2 ))"
+     ;;
+   *)
+     echo -e "${RED}CALC FUNCTION ERROR${NC}"    
+     exit 1
+     ;; 
+esac	
 }
 
 search() 
 {
-  local file_name=$param2
-  local pattern=$param3 
+  local file_name=$1
+  local pattern=$2
   grep -r $pattern $file_name 
 }
 
 reverse()
 {
-  local file_f=$param2
-  local file_s=$param3
+  local file_f=$1
+  local file_s=$2
   
   readarray arr < SearchMe/$file_f
   for ((i=${#arr[*]}; i >= 0; i--))
@@ -57,8 +80,8 @@ reverse()
 }
 
 strlen()
-{
-  echo | awk -v str="$param2" '{ print "String: " str }
+{ 
+  echo | awk -v str="$1" '{ print "String: " str }
                   			   { print "RESULT: " length(str)}'
 }
 
@@ -71,7 +94,7 @@ log()
  # tail -f war | GREP_COLOR='01;36' egrep --color=always 'Warnings|$'
   GREP_COLOR="1;33" grep --color="always" "Warnings" war >> color  
   GREP_COLOR="1;34" grep --color="always" "Information" war >> color
-  rm war  && head -n 5 color && tail -n 5 color && rm color 
+  rm war  && head -n 7 color && tail -n 10 color && rm color 
  # echo "Warnings" | awk '{ gsub("Warnings", "\033[1;33m&\033[0m"); print }'
 }
 
@@ -94,38 +117,110 @@ help()
       
         ${LBLUE}exit${NC}    - [return code]                 ${ORANGE}/* exit programm with code         */${NC}   
 
-        ${YELLOW}=============================================================================${NC}
-  "
+        ${YELLOW}=============================================================================${NC} "
+}
+
+exit_code() 
+{
+ if [ -z "$1" ]
+ then  
+   echo "exit code: 0"
+   exit 0
+ else
+   echo "exit code: $1"
+   exit $param2
+  fi 
+}
+
+menu_draw()
+{
+  echo -e "
+  a - calc
+  b - search
+  c - reverse
+  d - strlen 
+  e - log 
+  f - exit
+  g - help 
+"
 }
 
 interactive()
 {
-  echo -e "
-1 - calc
-2 - search
-3 - reverse
-4 - strlen
-5 - log
-6 - exit "
-
+  menu_draw
+  read -r key
+  
+  case $key in 
+  a | calc)
+    echo -e "Input operation for numbers: \c"
+    read -r oper
+    echo -e  "Input first num: \c"
+    read -r arg1
+    echo -e "Input second num: \c"
+    read -r arg2 
+    calc "$oper" "$arg1" "$arg2" 
+    interactive  
+    ;;
+  b | search)
+    echo -e "Input dirictory name: \c"
+    read -r dir_name
+    echo -e "Input expresion: \c"
+    read -r ex
+    search "$dir_name" "$ex"   i
+    interactive
+    ;;
+  c | reverse) 
+    echo -e "Input first file name: \c"
+    read -r file_f
+    echo -e "Input second file name: \c"
+    read -r file_s
+    reverse "$file_f" "$file_s"
+    interactive
+    ;;
+  d | strlen) 
+    echo -e "Input string: \c" 
+    read -r str 
+    strlen "$str" 
+    interactive
+    ;;
+  e | log)
+    log 
+    interactive 
+    ;;
+  f | exit)
+    echo -e "Input parameter: \c"
+    read -r input
+    clear 
+    exit_code "$input"
+    ;;
+  g | help)
+    help
+    interactive 
+    ;; 
+  *) 
+    echo -e "${RED}NO SUCH KEY ${NC}"
+    interactive
+ esac
 }
 
-case $param1 in 
+call_func=$1
+param2=$2
+ case $call_func in
   calc)
-    clear		 
-    calc
+    clear
+    calc "$2" "$3" "$4"
     ;;
   search)
     clear
-    search
+    search "$2" "$3"
     ;;
   reverse)
     clear
-    reverse 
+    reverse "$2" "$3"
     ;;
   strlen)
     clear
-    strlen 
+    strlen "$2" 
     ;;
   log) 
     clear
@@ -133,27 +228,20 @@ case $param1 in
     ;;
   exit)
     clear
-    if [ -z "$param2" ]
-    then 
-      echo "exit code: 0"
-      exit 0
-    else
-      echo "exit code: $param2"
-      exit $param2
-    fi  
+    exit_code "$2"
     ;;
   help)
     clear
     help 
     ;; 
-  interactive)
-    interactive 
+  interactive) 
+    clear
+    interactive
     ;; 
   *)
     clear
-    echo -e "${RED}SECOND PARAMETER DOSN'T EXIST/NONE${NC}"
-    exit 1
+    help
+    echo -e "${RED} YOU TYPED FUNCTION DOESN'T EXIST ${NC}"
     ;;
 esac
-
 
